// Code generated by ogen, DO NOT EDIT.
package api

type AddBankBackgroundRes interface {
	addBankBackgroundRes()
}

type AuditLogStatsRes interface {
	auditLogStatsRes()
}

type CancelOperationRes interface {
	cancelOperationRes()
}

type ClearBankMemoriesRes interface {
	clearBankMemoriesRes()
}

type ClearMemoryObservationsRes interface {
	clearMemoryObservationsRes()
}

type ClearMentalModelRes interface {
	clearMentalModelRes()
}

type ClearObservationsRes interface {
	clearObservationsRes()
}

type CloneBankRes interface {
	cloneBankRes()
}

type CreateBankAliasRes interface {
	createBankAliasRes()
}

type CreateDirectiveRes interface {
	createDirectiveRes()
}

type CreateKnowledgeFolderRes interface {
	createKnowledgeFolderRes()
}

type CreateKnowledgePageRes interface {
	createKnowledgePageRes()
}

type CreateMentalModelRes interface {
	createMentalModelRes()
}

type CreateOrUpdateBankRes interface {
	createOrUpdateBankRes()
}

type CreateWebhookRes interface {
	createWebhookRes()
}

type DeleteBankAliasRes interface {
	deleteBankAliasRes()
}

type DeleteBankRes interface {
	deleteBankRes()
}

type DeleteDirectiveRes interface {
	deleteDirectiveRes()
}

type DeleteDocumentRes interface {
	deleteDocumentRes()
}

type DeleteKnowledgeNodeRes interface {
	deleteKnowledgeNodeRes()
}

type DeleteMentalModelRes interface {
	deleteMentalModelRes()
}

type DeleteOperationRes interface {
	deleteOperationRes()
}

type DeleteWebhookRes interface {
	deleteWebhookRes()
}

type DownloadFileRes interface {
	downloadFileRes()
}

type DryRunExtractMemoriesRes interface {
	dryRunExtractMemoriesRes()
}

type DryRunRefreshMentalModelRes interface {
	dryRunRefreshMentalModelRes()
}

type ExportBankTemplateRes interface {
	exportBankTemplateRes()
}

type ExportBankTransferRes interface {
	exportBankTransferRes()
}

type ExportDocumentsRes interface {
	exportDocumentsRes()
}

type ExportDocumentsSyncRemovedRes interface {
	exportDocumentsSyncRemovedRes()
}

type ExportKnowledgeBaseRes interface {
	exportKnowledgeBaseRes()
}

type FileRetainRes interface {
	fileRetainRes()
}

type GetAgentStatsRes interface {
	getAgentStatsRes()
}

type GetBankAttachmentRes interface {
	getBankAttachmentRes()
}

type GetBankConfigRes interface {
	getBankConfigRes()
}

type GetBankProfileRes interface {
	getBankProfileRes()
}

type GetChunkRes interface {
	getChunkRes()
}

type GetDirectiveRes interface {
	getDirectiveRes()
}

type GetDocumentRes interface {
	getDocumentRes()
}

type GetEntityGraphRes interface {
	getEntityGraphRes()
}

type GetEntityRes interface {
	getEntityRes()
}

type GetGraphRes interface {
	getGraphRes()
}

type GetKnowledgeBaseTreeRes interface {
	getKnowledgeBaseTreeRes()
}

type GetKnowledgePageRes interface {
	getKnowledgePageRes()
}

type GetMemoriesTimeseriesRes interface {
	getMemoriesTimeseriesRes()
}

type GetMemoryRes interface {
	getMemoryRes()
}

type GetMentalModelHistoryRes interface {
	getMentalModelHistoryRes()
}

type GetMentalModelRes interface {
	getMentalModelRes()
}

type GetObservationHistoryRes interface {
	getObservationHistoryRes()
}

type GetOperationStatusRes interface {
	getOperationStatusRes()
}

type ImportBankTemplateRes interface {
	importBankTemplateRes()
}

type ImportBankTransferRes interface {
	importBankTransferRes()
}

type ImportDocumentsRes interface {
	importDocumentsRes()
}

type ListAuditLogsRes interface {
	listAuditLogsRes()
}

type ListBankAliasesRes interface {
	listBankAliasesRes()
}

type ListBanksRes interface {
	listBanksRes()
}

type ListDirectivesRes interface {
	listDirectivesRes()
}

type ListDocumentChunksRes interface {
	listDocumentChunksRes()
}

type ListDocumentsRes interface {
	listDocumentsRes()
}

type ListEntitiesRes interface {
	listEntitiesRes()
}

type ListLlmRequestsRes interface {
	listLlmRequestsRes()
}

type ListMemoriesRes interface {
	listMemoriesRes()
}

type ListMentalModelsRes interface {
	listMentalModelsRes()
}

type ListObservationScopesRes interface {
	listObservationScopesRes()
}

type ListOperationsRes interface {
	listOperationsRes()
}

type ListTagsRes interface {
	listTagsRes()
}

type ListWebhookDeliveriesRes interface {
	listWebhookDeliveriesRes()
}

type ListWebhooksRes interface {
	listWebhooksRes()
}

type LlmRequestStatsRes interface {
	llmRequestStatsRes()
}

type PreviewConsolidationStrategiesRes interface {
	previewConsolidationStrategiesRes()
}

type PreviewPromptRes interface {
	previewPromptRes()
}

type RecallMemoriesRes interface {
	recallMemoriesRes()
}

type RecoverConsolidationRes interface {
	recoverConsolidationRes()
}

type ReflectRes interface {
	reflectRes()
}

type RefreshMentalModelRes interface {
	refreshMentalModelRes()
}

type RegenerateEntityObservationsRes interface {
	regenerateEntityObservationsRes()
}

type ReprocessDocumentRes interface {
	reprocessDocumentRes()
}

type ResetBankConfigRes interface {
	resetBankConfigRes()
}

type RetainMemoriesRes interface {
	retainMemoriesRes()
}

type RetryOperationRes interface {
	retryOperationRes()
}

type SearchKnowledgeBaseRes interface {
	searchKnowledgeBaseRes()
}

type SetBankAliasPrimaryRes interface {
	setBankAliasPrimaryRes()
}

type TestBankLlmRes interface {
	testBankLlmRes()
}

type TriggerConsolidationRes interface {
	triggerConsolidationRes()
}

type UpdateBankConfigRes interface {
	updateBankConfigRes()
}

type UpdateBankDispositionRes interface {
	updateBankDispositionRes()
}

type UpdateBankRes interface {
	updateBankRes()
}

type UpdateDirectiveRes interface {
	updateDirectiveRes()
}

type UpdateDocumentRes interface {
	updateDocumentRes()
}

type UpdateKnowledgeNodeRes interface {
	updateKnowledgeNodeRes()
}

type UpdateMemoryRes interface {
	updateMemoryRes()
}

type UpdateMentalModelRes interface {
	updateMentalModelRes()
}

type UpdateWebhookRes interface {
	updateWebhookRes()
}
