// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	"github.com/go-faster/jx"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// AddBankBackground implements add_bank_background operation.
	//
	// Removed. The bank background was folded into the reflect mission. Write it with PATCH
	// /v1/default/banks/{bank_id}/config as `reflect_mission`. That call replaces the value rather than
	// merging into it, so read the current mission from GET .../config first if you relied on this
	// endpoint's append behaviour.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/default/banks/{bank_id}/background
	AddBankBackground(ctx context.Context, req *AddBackgroundRequest, params AddBankBackgroundParams) (AddBankBackgroundRes, error)
	// AuditLogStats implements audit_log_stats operation.
	//
	// Get audit log counts grouped by time bucket for charting.
	//
	// GET /v1/default/banks/{bank_id}/audit-logs/stats
	AuditLogStats(ctx context.Context, params AuditLogStatsParams) (AuditLogStatsRes, error)
	// CancelOperation implements cancel_operation operation.
	//
	// Cancel a queued or running async operation. A 'pending' operation is never started. A 'processing'
	// one is cancelled cooperatively: the row is marked 'cancelled' immediately and the worker running it
	// stops at its next checkpoint, so work already in flight may finish the batch it is on. This also
	// clears operations stranded in 'processing' by a crashed worker. Returns 409 for operations that
	// already reached a terminal state.
	//
	// DELETE /v1/default/banks/{bank_id}/operations/{operation_id}
	CancelOperation(ctx context.Context, params CancelOperationParams) (CancelOperationRes, error)
	// ClearBankMemories implements clear_bank_memories operation.
	//
	// Delete memory units for a memory bank. Optionally filter by type (world, experience, observation) to
	// delete only specific types. This is a destructive operation that cannot be undone. The bank profile
	// (disposition and background) will be preserved.
	//
	// DELETE /v1/default/banks/{bank_id}/memories
	ClearBankMemories(ctx context.Context, params ClearBankMemoriesParams) (ClearBankMemoriesRes, error)
	// ClearMemoryObservations implements clear_memory_observations operation.
	//
	// Delete all observations derived from a specific memory and reset it for re-consolidation. The memory
	// itself is not deleted. A consolidation job is triggered automatically so the memory will produce
	// fresh observations on the next consolidation run.
	//
	// DELETE /v1/default/banks/{bank_id}/memories/{memory_id}/observations
	ClearMemoryObservations(ctx context.Context, params ClearMemoryObservationsParams) (ClearMemoryObservationsRes, error)
	// ClearMentalModel implements clear_mental_model operation.
	//
	// Clear a mental model's content so the next refresh performs a full re-synthesis. This is useful for
	// delta-mode models that have accumulated drift over many incremental refreshes. After clearing, call
	// the /refresh endpoint to trigger a clean full rebuild.
	//
	// POST /v1/default/banks/{bank_id}/mental-models/{mental_model_id}/clear
	ClearMentalModel(ctx context.Context, params ClearMentalModelParams) (ClearMentalModelRes, error)
	// ClearObservations implements clear_observations operation.
	//
	// Delete all observations for a memory bank. This is useful for resetting the consolidated knowledge.
	//
	// DELETE /v1/default/banks/{bank_id}/observations
	ClearObservations(ctx context.Context, params ClearObservationsParams) (ClearObservationsRes, error)
	// CloneBank implements clone_bank operation.
	//
	// Copy this bank into a new one, in a single call. The clone starts with the source's memories as they
	// are at clone time and evolves independently from then on: later retains, consolidation and edits on
	// either bank leave the other alone.
	//
	// This is the export and import above run back to back on this instance, so nothing is re-extracted
	// and no LLM is called — facts are re-embedded and entities re-resolved, exactly as a restore does.
	// The same three flags choose what the clone inherits: include_data (documents, facts, observations,
	// attachments, the curation archive, the operations log, and the mental models and knowledge pages
	// synthesized from them), include_bank_config (the bank's config overrides, directives and webhooks)
	// and include_history (audit_log, llm_requests).
	//
	// Note the webhooks: they travel with the bank's configuration, so a clone made with the default flags
	// will call the source's webhook endpoints. Pass include_bank_config=false, or delete them on the
	// clone, when they point at a per-bank consumer.
	//
	// target_bank_id must not already exist. Returns an operation_id, recorded against the source bank
	// (the target does not exist yet); poll GET /v1/default/banks/{bank_id}/operations/{operation_id} for
	// status and the per-component counts.
	//
	// POST /v1/default/banks/{bank_id}/clone
	CloneBank(ctx context.Context, params CloneBankParams) (CloneBankRes, error)
	// CreateBankAlias implements create_bank_alias operation.
	//
	// Give the bank another id to answer to. Nothing is copied or moved: the bank keeps its own id and all
	// of its data, and the alias is only a second way to reach it — which is what makes it a
	// zero-downtime alternative to renaming.
	//
	// Returns 409 if the name is already a bank or another alias.
	//
	// POST /v1/default/banks/{bank_id}/aliases
	CreateBankAlias(ctx context.Context, req *CreateBankAliasRequest, params CreateBankAliasParams) (CreateBankAliasRes, error)
	// CreateDirective implements create_directive operation.
	//
	// Create a global or tag-scoped hard rule for reflect prompts.
	//
	// POST /v1/default/banks/{bank_id}/directives
	CreateDirective(ctx context.Context, req *CreateDirectiveRequest, params CreateDirectiveParams) (CreateDirectiveRes, error)
	// CreateKnowledgeFolder implements create_knowledge_folder operation.
	//
	// Create a folder, optionally nested under a parent folder.
	//
	// POST /v1/default/banks/{bank_id}/knowledge-base/folders
	CreateKnowledgeFolder(ctx context.Context, req *CreateFolderRequest, params CreateKnowledgeFolderParams) (CreateKnowledgeFolderRes, error)
	// CreateKnowledgePage implements create_knowledge_page operation.
	//
	// Create a page (a mental model + tree node). Content is generated asynchronously; use the returned
	// operation_id to track completion.
	//
	// POST /v1/default/banks/{bank_id}/knowledge-base/pages
	CreateKnowledgePage(ctx context.Context, req *CreatePageRequest, params CreateKnowledgePageParams) (CreateKnowledgePageRes, error)
	// CreateMentalModel implements create_mental_model operation.
	//
	// Create a mental model by running reflect with the source query in the background. Returns an
	// operation ID to track progress. The content is auto-generated by the reflect endpoint. Use the
	// operations endpoint to check completion status.
	//
	// POST /v1/default/banks/{bank_id}/mental-models
	CreateMentalModel(ctx context.Context, req *CreateMentalModelRequest, params CreateMentalModelParams) (CreateMentalModelRes, error)
	// CreateOrUpdateBank implements create_or_update_bank operation.
	//
	// Create a new agent or update existing agent with disposition and mission. Auto-fills missing fields
	// with defaults.
	//
	// PUT /v1/default/banks/{bank_id}
	CreateOrUpdateBank(ctx context.Context, req *CreateBankRequest, params CreateOrUpdateBankParams) (CreateOrUpdateBankRes, error)
	// CreateWebhook implements create_webhook operation.
	//
	// Register a webhook endpoint to receive event notifications for this bank.
	//
	// POST /v1/default/banks/{bank_id}/webhooks
	CreateWebhook(ctx context.Context, req *CreateWebhookRequest, params CreateWebhookParams) (CreateWebhookRes, error)
	// DeleteBank implements delete_bank operation.
	//
	// Delete an entire memory bank including all memories, entities, documents, and the bank profile
	// itself. This is a destructive operation that cannot be undone.
	//
	// DELETE /v1/default/banks/{bank_id}
	DeleteBank(ctx context.Context, params DeleteBankParams) (DeleteBankRes, error)
	// DeleteBankAlias implements delete_bank_alias operation.
	//
	// Stop an id reaching this bank. The bank and its memories are untouched; only the extra name goes
	// away, and callers still using it get the same 404 (or new empty bank) they would have got before it
	// existed.
	//
	// DELETE /v1/default/banks/{bank_id}/aliases/{alias}
	DeleteBankAlias(ctx context.Context, params DeleteBankAliasParams) (DeleteBankAliasRes, error)
	// DeleteDirective implements delete_directive operation.
	//
	// Delete a directive.
	//
	// DELETE /v1/default/banks/{bank_id}/directives/{directive_id}
	DeleteDirective(ctx context.Context, params DeleteDirectiveParams) (DeleteDirectiveRes, error)
	// DeleteDocument implements delete_document operation.
	//
	// Delete a document and all its associated memory units and links.
	//
	// This will cascade delete:
	//
	//  - The document itself
	//  - All memory units extracted from this document
	//  - All links (temporal, semantic, entity) associated with those memory units
	//
	// This operation cannot be undone.
	//
	// DELETE /v1/default/banks/{bank_id}/documents/{document_id}
	DeleteDocument(ctx context.Context, params DeleteDocumentParams) (DeleteDocumentRes, error)
	// DeleteKnowledgeNode implements delete_knowledge_node operation.
	//
	// Delete a folder or page and its whole subtree (pages' mental models are removed too).
	//
	// DELETE /v1/default/banks/{bank_id}/knowledge-base/nodes/{node_id}
	DeleteKnowledgeNode(ctx context.Context, params DeleteKnowledgeNodeParams) (DeleteKnowledgeNodeRes, error)
	// DeleteMentalModel implements delete_mental_model operation.
	//
	// Delete a mental model.
	//
	// DELETE /v1/default/banks/{bank_id}/mental-models/{mental_model_id}
	DeleteMentalModel(ctx context.Context, params DeleteMentalModelParams) (DeleteMentalModelRes, error)
	// DeleteOperation implements delete_operation operation.
	//
	// Permanently remove a failed, cancelled, or completed async operation record.
	//
	// DELETE /v1/default/banks/{bank_id}/operations/{operation_id}/delete
	DeleteOperation(ctx context.Context, params DeleteOperationParams) (DeleteOperationRes, error)
	// DeleteWebhook implements delete_webhook operation.
	//
	// Remove a registered webhook.
	//
	// DELETE /v1/default/banks/{bank_id}/webhooks/{webhook_id}
	DeleteWebhook(ctx context.Context, params DeleteWebhookParams) (DeleteWebhookRes, error)
	// DownloadFile implements download_file operation.
	//
	// Stream a file previously written to file storage — currently the transfer ZIP produced by an async
	// document export. The key comes from the export operation's result_metadata (storage_key /
	// download_url). Access is authorized against the bank the key belongs to.
	//
	// GET /v1/default/files/download/{key}
	DownloadFile(ctx context.Context, params DownloadFileParams) (DownloadFileRes, error)
	// DryRunExtractMemories implements dry_run_extract_memories operation.
	//
	// Preview what the retain step would extract from text WITHOUT changing the bank — no entity
	// resolution, links, embeddings, or persistence. Returns the candidate facts and the LLM token usage.
	// Every prompt-affecting setting (retain mission, extraction mode, chunk size, …) is overridable in
	// the body to A/B a candidate config against the bank's current one. This is a read-only tool: nothing
	// is stored.
	//
	// POST /v1/default/banks/{bank_id}/memories/dry-run-extract
	DryRunExtractMemories(ctx context.Context, req *DryRunExtractRequest, params DryRunExtractMemoriesParams) (DryRunExtractMemoriesRes, error)
	// DryRunRefreshMentalModel implements dry_run_refresh_mental_model operation.
	//
	// Preview what a refresh would do to this mental model WITHOUT changing it — no content, structured
	// document, watermark, or last_refreshed_at is written. Returns the mode the refresh ran in and why
	// (delta silently falls back to full when there is no baseline or the source query changed), the
	// resolved tag scope and time window it read, how many facts retrieval returned versus how many the
	// reflect agent actually used, the delta operations it emitted, and a unified diff from the stored
	// content to the content it would write.
	//
	// This is the production refresh pipeline with two writes skipped — the content and the watermark
	// — and nothing about it is configurable, so what it reports is what the next refresh will do.
	// Because nothing is persisted, a delta dry run reads exactly the window the next real refresh would,
	// and repeating it reads that same window again.
	//
	// It costs the same LLM tokens as a refresh and is validated the same way.
	//
	// POST /v1/default/banks/{bank_id}/mental-models/{mental_model_id}/dry-run-refresh
	DryRunRefreshMentalModel(ctx context.Context, params DryRunRefreshMentalModelParams) (DryRunRefreshMentalModelRes, error)
	// ExportBankTemplate implements export_bank_template operation.
	//
	// Export a bank's current configuration, mental models, and directives as a template manifest. The
	// exported manifest can be imported into another bank to replicate the setup.
	//
	// GET /v1/default/banks/{bank_id}/export
	ExportBankTemplate(ctx context.Context, params ExportBankTemplateParams) (ExportBankTemplateRes, error)
	// ExportBankTransfer implements export_bank_transfer operation.
	//
	// Submit an async export of a bank as a transfer ZIP archive. Three flags choose what the archive
	// carries: include_data (documents, facts, observations, attachments and their bytes, the curation
	// archive, the operations log and the maintenance queues), include_bank_config (bank config, mental
	// models and their history, knowledge pages), include_bank_config (the bank's config overrides,
	// directives and webhooks) and include_history (audit_log, llm_requests). Embeddings and database ids
	// are never carried — importing re-embeds with the target bank's model and re-resolves entities, so
	// an archive moves between instances configured with different embedding models. Returns an
	// operation_id; poll GET /v1/default/banks/{bank_id}/operations/{operation_id}, then fetch the archive
	// from the download_url in its result_metadata. Pass document_id to export specific documents instead
	// of the whole bank (a document subset carries no bank-level sections).
	//
	// POST /v1/default/banks/{bank_id}/transfer/export
	ExportBankTransfer(ctx context.Context, params ExportBankTransferParams) (ExportBankTransferRes, error)
	// ExportDocuments implements export_documents operation.
	//
	// Submit an async export of a bank's documents (extracted facts, entity names, causal links, chunks)
	// as a transfer ZIP archive. Embeddings and database ids are not included — importing re-embeds with
	// the target bank's model and re-resolves entities. Runs as a background operation to avoid pinning
	// the API on large banks. Returns an operation_id; poll GET
	// /v1/default/banks/{bank_id}/operations/{operation_id}. On completion the operation's result_metadata
	// carries download_url (fetch the ZIP from GET /v1/default/files/download/{key}), storage_key,
	// byte_size, and filename. Pass document_id query params to export specific documents, or omit to
	// export the whole bank; include_observations=true carries consolidated observations and
	// include_knowledge_base=true carries Mental Models plus Knowledge Pages (all whole-bank export only).
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/default/banks/{bank_id}/document-transfer/export
	ExportDocuments(ctx context.Context, params ExportDocumentsParams) (ExportDocumentsRes, error)
	// ExportDocumentsSyncRemoved implements export_documents_sync_removed operation.
	//
	// Removed. The synchronous whole-bank export loaded the entire bank into memory and held a database
	// connection for the full request, which could exhaust memory and take down the shared API on large
	// banks. Use the asynchronous POST /v1/default/banks/{bank_id}/document-transfer/export instead: it
	// returns an operation_id, runs the export in the background, and exposes a download URL on
	// completion.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /v1/default/banks/{bank_id}/document-transfer
	ExportDocumentsSyncRemoved(ctx context.Context, params ExportDocumentsSyncRemovedParams) (ExportDocumentsSyncRemovedRes, error)
	// ExportKnowledgeBase implements export_knowledge_base operation.
	//
	// Return a portable markdown bundle: a nested index.md, one .md per page, and history logs.
	//
	// GET /v1/default/banks/{bank_id}/knowledge-base/export
	ExportKnowledgeBase(ctx context.Context, params ExportKnowledgeBaseParams) (ExportKnowledgeBaseRes, error)
	// FileRetain implements file_retain operation.
	//
	// Upload files (PDF, DOCX, etc.), convert them to markdown, and retain as memories.
	//
	// This endpoint handles file upload, conversion, and memory creation in a single operation.
	//
	// Features:
	//
	//  - Supports PDF, DOCX, PPTX, XLSX, images (parser-dependent OCR), audio (with transcription)
	//  - Automatic file-to-markdown conversion using pluggable parsers
	//  - Files stored in object storage (PostgreSQL by default, S3 for production)
	//  - Each file becomes a separate document with optional metadata/tags
	//  - Always processes asynchronously — returns operation IDs immediately
	//
	// The system automatically:
	//
	// 1. Stores uploaded files in object storage
	// 2. Converts files to markdown
	// 3. Creates document records with file metadata
	// 4. Extracts facts and creates memory units (same as regular retain)
	//
	// Use the operations endpoint to monitor progress.
	//
	// Request format: multipart/form-data with:
	//
	//  - `files`: One or more files to upload
	//  - `request`: JSON string with FileRetainRequest model
	//
	// Parser selection:
	//
	//  - Set `parser` in the request body to override the server default for all files.
	//  - Set `parser` inside a `files_metadata` entry for per-file control.
	//  - Pass a list (e.g. `['iris', 'markitdown']`) to define an ordered fallback chain — each parser
	//    is tried in sequence until one succeeds.
	//  - Falls back to the server default (`HINDSIGHT_API_FILE_PARSER`) if not specified.
	//  - Only parsers enabled on the server may be requested; others return HTTP 400.
	//
	// POST /v1/default/banks/{bank_id}/files/retain
	FileRetain(ctx context.Context, req *BodyFileRetainMultipart, params FileRetainParams) (FileRetainRes, error)
	// GetAgentStats implements get_agent_stats operation.
	//
	// Get statistics about nodes and links for a specific agent.
	//
	// GET /v1/default/banks/{bank_id}/stats
	GetAgentStats(ctx context.Context, params GetAgentStatsParams) (GetAgentStatsRes, error)
	// GetBankAttachment implements get_bank_attachment operation.
	//
	// Serve the bytes of an attachment retained as inline content. The id is the one inside a placeholder
	// token, and is returned on `attachments[].url` by recall and by the document/chunk/memory reads —
	// so an agent can show or reason over the original behind an attachment-derived fact.
	//
	// Bytes are served with the Content-Type the caller declared at retain. Access is authorized against
	// the bank; a missing attachment and an invisible bank both return 404, so the endpoint cannot be used
	// to probe what a bank holds.
	//
	// GET /v1/default/banks/{bank_id}/attachments/{attachment_id}
	GetBankAttachment(ctx context.Context, params GetBankAttachmentParams) (GetBankAttachmentRes, error)
	// GetBankConfig implements get_bank_config operation.
	//
	// Get fully resolved configuration for a bank including all hierarchical overrides (global → tenant
	// → bank). The 'config' field contains all resolved config values. The 'overrides' field shows only
	// bank-specific overrides. Always available: HINDSIGHT_API_ENABLE_BANK_CONFIG_API gates only the write
	// operations on this resource.
	//
	// GET /v1/default/banks/{bank_id}/config
	GetBankConfig(ctx context.Context, params GetBankConfigParams) (GetBankConfigRes, error)
	// GetBankProfile implements get_bank_profile operation.
	//
	// Removed. The bank profile endpoints have been removed. Disposition traits and the reflect mission
	// are bank configuration: read them from GET /v1/default/banks/{bank_id}/config as
	// `disposition_skepticism`, `disposition_literalism`, `disposition_empathy` and `reflect_mission`, and
	// write them with PATCH /v1/default/banks/{bank_id}/config. The `name` field this endpoint also
	// returned was a display-only label; read it from GET /v1/default/banks.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// GET /v1/default/banks/{bank_id}/profile
	GetBankProfile(ctx context.Context, params GetBankProfileParams) (GetBankProfileRes, error)
	// GetBankTemplateSchema implements get_bank_template_schema operation.
	//
	// Returns the JSON Schema for the bank template manifest format. Use this to validate template
	// manifests before importing.
	//
	// GET /v1/bank-template-schema
	GetBankTemplateSchema(ctx context.Context) (jx.Raw, error)
	// GetChunk implements get_chunk operation.
	//
	// Get a specific chunk by its ID.
	//
	// GET /v1/default/chunks/{chunk_id}
	GetChunk(ctx context.Context, params GetChunkParams) (GetChunkRes, error)
	// GetDirective implements get_directive operation.
	//
	// Get a specific directive by ID.
	//
	// GET /v1/default/banks/{bank_id}/directives/{directive_id}
	GetDirective(ctx context.Context, params GetDirectiveParams) (GetDirectiveRes, error)
	// GetDocument implements get_document operation.
	//
	// Get a specific document including its original text.
	//
	// GET /v1/default/banks/{bank_id}/documents/{document_id}
	GetDocument(ctx context.Context, params GetDocumentParams) (GetDocumentRes, error)
	// GetEntity implements get_entity operation.
	//
	// Get detailed information about an entity including observations (mental model).
	//
	// GET /v1/default/banks/{bank_id}/entities/{entity_id}
	GetEntity(ctx context.Context, params GetEntityParams) (GetEntityRes, error)
	// GetEntityGraph implements get_entity_graph operation.
	//
	// Return a graph of entities (nodes) and their co-occurrences (edges) for visualization.
	//
	// GET /v1/default/banks/{bank_id}/entities/graph
	GetEntityGraph(ctx context.Context, params GetEntityGraphParams) (GetEntityGraphRes, error)
	// GetGraph implements get_graph operation.
	//
	// Retrieve graph data for visualization, optionally filtered by type (world/experience/observation).
	//
	// GET /v1/default/banks/{bank_id}/graph
	GetGraph(ctx context.Context, params GetGraphParams) (GetGraphRes, error)
	// GetKnowledgeBaseTree implements get_knowledge_base_tree operation.
	//
	// Return the knowledge base as a nested tree of folders and pages.
	//
	// GET /v1/default/banks/{bank_id}/knowledge-base/tree
	GetKnowledgeBaseTree(ctx context.Context, params GetKnowledgeBaseTreeParams) (GetKnowledgeBaseTreeRes, error)
	// GetKnowledgePage implements get_knowledge_page operation.
	//
	// Return a single page as a markdown document (frontmatter + markdown body).
	//
	// GET /v1/default/banks/{bank_id}/knowledge-base/pages/{page_id}
	GetKnowledgePage(ctx context.Context, params GetKnowledgePageParams) (GetKnowledgePageRes, error)
	// GetLiveness implements get_liveness operation.
	//
	// Returns 200 whenever the process can serve a request. Performs no database access, so a slow or
	// unreachable database never restarts the pod. Point livenessProbe here and readinessProbe at /health.
	//
	// GET /health/live
	GetLiveness(ctx context.Context) (*LivenessResponse, error)
	// GetMemoriesTimeseries implements get_memories_timeseries operation.
	//
	// Memories ingested over a period, bucketed by time and broken down by fact type.
	//
	// GET /v1/default/banks/{bank_id}/stats/memories-timeseries
	GetMemoriesTimeseries(ctx context.Context, params GetMemoriesTimeseriesParams) (GetMemoriesTimeseriesRes, error)
	// GetMemory implements get_memory operation.
	//
	// Get a single memory unit by ID with all its metadata including entities and tags. Note: the
	// 'history' field is deprecated and always returns an empty list - use GET
	// /memories/{memory_id}/history instead.
	//
	// GET /v1/default/banks/{bank_id}/memories/{memory_id}
	GetMemory(ctx context.Context, params GetMemoryParams) (GetMemoryRes, error)
	// GetMentalModel implements get_mental_model operation.
	//
	// Get a specific mental model by ID.
	//
	// GET /v1/default/banks/{bank_id}/mental-models/{mental_model_id}
	GetMentalModel(ctx context.Context, params GetMentalModelParams) (GetMentalModelRes, error)
	// GetMentalModelHistory implements get_mental_model_history operation.
	//
	// Get the refresh history of a mental model, showing content changes over time.
	//
	// GET /v1/default/banks/{bank_id}/mental-models/{mental_model_id}/history
	GetMentalModelHistory(ctx context.Context, params GetMentalModelHistoryParams) (GetMentalModelHistoryRes, error)
	// GetObservationHistory implements get_observation_history operation.
	//
	// Get the full history of an observation, with each change's source facts resolved to their text.
	//
	// GET /v1/default/banks/{bank_id}/memories/{memory_id}/history
	GetObservationHistory(ctx context.Context, params GetObservationHistoryParams) (GetObservationHistoryRes, error)
	// GetOperationStatus implements get_operation_status operation.
	//
	// Get the status of a specific async operation. Returns 'pending', 'processing', 'completed',
	// 'failed', or 'cancelled'. Completed operations remain queryable with their payload for the
	// configured retention window and are pruned afterward.
	//
	// GET /v1/default/banks/{bank_id}/operations/{operation_id}
	GetOperationStatus(ctx context.Context, params GetOperationStatusParams) (GetOperationStatusRes, error)
	// GetReadiness implements get_readiness operation.
	//
	// Returns 200 when the API can serve traffic (database reachable), 503 otherwise. Identical to
	// /health, which stays supported as its alias.
	//
	// GET /health/ready
	GetReadiness(ctx context.Context) (jx.Raw, error)
	// GetVersion implements get_version operation.
	//
	// Returns API version information and enabled feature flags. Use this to check which capabilities are
	// available in this deployment.
	//
	// GET /version
	GetVersion(ctx context.Context) (*VersionResponse, error)
	// HealthEndpointHealthGet implements health_endpoint_health_get operation.
	//
	// Readiness check: verifies the API can reach the database. Alias of /health/ready. Use /health/live
	// for liveness probes — this one fails whenever the database is unreachable, which must gate
	// traffic, not restart the process.
	//
	// GET /health
	HealthEndpointHealthGet(ctx context.Context) (jx.Raw, error)
	// ImportBankTemplate implements import_bank_template operation.
	//
	// Import a bank template manifest to create or update a bank's configuration, mental models, and
	// directives. If the bank does not exist it is created. Config fields are applied as per-bank
	// overrides. Mental models are matched by id, directives by name — existing ones are updated, new
	// ones are created. Use dry_run=true to validate the manifest without applying changes.
	//
	// POST /v1/default/banks/{bank_id}/import
	ImportBankTemplate(ctx context.Context, req *BankTemplateManifest, params ImportBankTemplateParams) (ImportBankTemplateRes, error)
	// ImportBankTransfer implements import_bank_transfer operation.
	//
	// Submit a transfer archive (produced by the export endpoint) for import. Runs as a background
	// operation: facts are re-embedded with the target bank's embedding model and entities are re-resolved
	// — no LLM extraction, so the import costs no tokens and invents no new facts.
	//
	// Two modes. `restore` (default) writes a whole bank into target_bank_id, which must NOT already exist
	// — it restores a bank rather than merging into one, and is how a bank is moved between instances or
	// copied under a new id. `merge` folds an archive's documents into this bank, with document_conflict
	// deciding what happens to ids that already exist (skip, replace, new-id).
	//
	// The include flags narrow what is restored to a subset of what the archive holds; they cannot add
	// what the producer did not export. Returns an operation_id; poll GET
	// /v1/default/banks/{bank_id}/operations/{operation_id} for status and per-component counts. The
	// operation is recorded against {bank_id} even in restore mode, because the target bank does not exist
	// yet.
	//
	// POST /v1/default/banks/{bank_id}/transfer/import
	ImportBankTransfer(ctx context.Context, req *BodyImportBankTransferMultipart, params ImportBankTransferParams) (ImportBankTransferRes, error)
	// ImportDocuments implements import_documents operation.
	//
	// Submit a transfer archive (produced by the export endpoint) for import into a bank. Runs as a
	// background operation: facts are re-embedded with the target bank's embedding model and entities are
	// re-resolved — no LLM extraction. Returns an operation_id; poll GET
	// /v1/default/banks/{bank_id}/operations/{operation_id} for status and the imported/skipped counts in
	// result_metadata. Use on_conflict to control existing document ids: skip (default), replace, or
	// new-id.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/default/banks/{bank_id}/document-transfer
	ImportDocuments(ctx context.Context, req *BodyImportDocumentsMultipart, params ImportDocumentsParams) (ImportDocumentsRes, error)
	// ListAuditLogs implements list_audit_logs operation.
	//
	// List audit log entries for a bank, ordered by most recent first.
	//
	// GET /v1/default/banks/{bank_id}/audit-logs
	ListAuditLogs(ctx context.Context, params ListAuditLogsParams) (ListAuditLogsRes, error)
	// ListBankAliases implements list_bank_aliases operation.
	//
	// Extra bank ids that reach this bank. Every endpoint accepts an alias wherever it accepts a bank id,
	// so callers can be moved onto a new id in phases while the old one keeps working.
	//
	// GET /v1/default/banks/{bank_id}/aliases
	ListBankAliases(ctx context.Context, params ListBankAliasesParams) (ListBankAliasesRes, error)
	// ListBanks implements list_banks operation.
	//
	// List banks with their profiles and summary stats, most recently written first (`last_write_at`
	// descending), with pagination and optional search.
	//
	// GET /v1/default/banks
	ListBanks(ctx context.Context, params ListBanksParams) (ListBanksRes, error)
	// ListDirectives implements list_directives operation.
	//
	// List directive definitions. Unlike reflect, an omitted tag filter returns all directives.
	//
	// GET /v1/default/banks/{bank_id}/directives
	ListDirectives(ctx context.Context, params ListDirectivesParams) (ListDirectivesRes, error)
	// ListDocumentChunks implements list_document_chunks operation.
	//
	// List all chunks for a given document, ordered by chunk index.
	//
	// GET /v1/default/banks/{bank_id}/documents/{document_id}/chunks
	ListDocumentChunks(ctx context.Context, params ListDocumentChunksParams) (ListDocumentChunksRes, error)
	// ListDocuments implements list_documents operation.
	//
	// List documents with pagination, optional search, and an optional time window. Most recently written
	// first (`updated_at` descending) unless `time_field` selects another axis. Documents are the source
	// content from which memory units are extracted.
	//
	// GET /v1/default/banks/{bank_id}/documents
	ListDocuments(ctx context.Context, params ListDocumentsParams) (ListDocumentsRes, error)
	// ListEntities implements list_entities operation.
	//
	// List all entities (people, organizations, etc.) known by the bank, ordered by mention count.
	// Supports pagination.
	//
	// GET /v1/default/banks/{bank_id}/entities
	ListEntities(ctx context.Context, params ListEntitiesParams) (ListEntitiesRes, error)
	// ListLlmRequests implements list_llm_requests operation.
	//
	// List traced LLM requests for a bank, ordered by most recent first. Requires LLM request tracing to
	// be enabled (HINDSIGHT_API_LLM_TRACE_ENABLED).
	//
	// GET /v1/default/banks/{bank_id}/llm-requests
	ListLlmRequests(ctx context.Context, params ListLlmRequestsParams) (ListLlmRequestsRes, error)
	// ListMemories implements list_memories operation.
	//
	// List memory units with pagination and optional full-text search. Supports filtering by type, source
	// document, linked entity ID, and a time window. Results are sorted by most recent first (mentioned_at
	// DESC, then created_at DESC) unless a time window selects another axis.
	//
	// GET /v1/default/banks/{bank_id}/memories/list
	ListMemories(ctx context.Context, params ListMemoriesParams) (ListMemoriesRes, error)
	// ListMentalModels implements list_mental_models operation.
	//
	// List user-curated living documents that stay current.
	//
	// GET /v1/default/banks/{bank_id}/mental-models
	ListMentalModels(ctx context.Context, params ListMentalModelsParams) (ListMentalModelsRes, error)
	// ListObservationScopes implements list_observation_scopes operation.
	//
	// Enumerate the distinct scopes across a bank's observations. Each observation lives under a scope:
	// the exact set of tags it was consolidated with. Returns every distinct scope (tag order normalized)
	// with the number of observations in it; the empty tag list is the global/untagged scope. Use a
	// returned scope with the graph endpoint (tags= & tags_match=exact) to filter observations to exactly
	// that scope. Paged: `total` reports every distinct scope in the bank.
	//
	// GET /v1/default/banks/{bank_id}/observations/scopes
	ListObservationScopes(ctx context.Context, params ListObservationScopesParams) (ListObservationScopesRes, error)
	// ListOperations implements list_operations operation.
	//
	// Get a list of async operations for a specific agent, with optional filtering by status and operation
	// type. Results are sorted by most recent first.
	//
	// GET /v1/default/banks/{bank_id}/operations
	ListOperations(ctx context.Context, params ListOperationsParams) (ListOperationsRes, error)
	// ListTags implements list_tags operation.
	//
	// List all unique tags in a memory bank with usage counts. Supports wildcard search using '' (e.g.,
	// 'user:', '-fred', 'tag-2'). Case-insensitive. Use `source=mental_models` to list tags used on mental
	// models instead of memories.
	//
	// GET /v1/default/banks/{bank_id}/tags
	ListTags(ctx context.Context, params ListTagsParams) (ListTagsRes, error)
	// ListWebhookDeliveries implements list_webhook_deliveries operation.
	//
	// Inspect delivery history for a webhook (useful for debugging).
	//
	// GET /v1/default/banks/{bank_id}/webhooks/{webhook_id}/deliveries
	ListWebhookDeliveries(ctx context.Context, params ListWebhookDeliveriesParams) (ListWebhookDeliveriesRes, error)
	// ListWebhooks implements list_webhooks operation.
	//
	// List the webhooks registered for a bank, oldest first. Paged: `total` reports every webhook on the
	// bank.
	//
	// GET /v1/default/banks/{bank_id}/webhooks
	ListWebhooks(ctx context.Context, params ListWebhooksParams) (ListWebhooksRes, error)
	// LlmRequestStats implements llm_request_stats operation.
	//
	// Get LLM request counts grouped by time bucket and status for charting.
	//
	// GET /v1/default/banks/{bank_id}/llm-requests/stats
	LlmRequestStats(ctx context.Context, params LlmRequestStatsParams) (LlmRequestStatsRes, error)
	// MetricsEndpointMetricsGet implements metrics_endpoint_metrics_get operation.
	//
	// Exports metrics in Prometheus format for scraping.
	//
	// GET /metrics
	MetricsEndpointMetricsGet(ctx context.Context) (jx.Raw, error)
	// PreviewConsolidationStrategies implements preview_consolidation_strategies operation.
	//
	// Report which of the bank's existing observation scopes each consolidation strategy would apply to,
	// for a draft `consolidation_strategies` value (nothing is saved). Uses the same matching and
	// first-strategy-wins rule as consolidation. Scans up to 10,000 distinct scopes; `complete` is false
	// beyond that and the counts are lower bounds. Scopes with no observations yet do not exist and are
	// not counted.
	//
	// POST /v1/default/banks/{bank_id}/consolidation-strategies/preview
	PreviewConsolidationStrategies(ctx context.Context, req *ConsolidationStrategiesPreviewRequest, params PreviewConsolidationStrategiesParams) (PreviewConsolidationStrategiesRes, error)
	// PreviewPrompt implements preview_prompt operation.
	//
	// Render the exact system and user messages retain, consolidation or reflect would send for this bank,
	// without calling an LLM, reading memories, or changing anything. Everything that shapes the prompt
	// comes from the bank; the runtime data an operation would be given is a fixed placeholder. Both
	// messages are returned: retain and consolidation keep their system prompt bank-agnostic (one
	// provider-side cache serves every bank) and carry the mission in the user message instead.
	//
	// POST /v1/default/banks/{bank_id}/prompts/preview
	PreviewPrompt(ctx context.Context, req *PromptPreviewRequest, params PreviewPromptParams) (PreviewPromptRes, error)
	// RecallMemories implements recall_memories operation.
	//
	// Recall memory using semantic similarity and spreading activation.
	//
	// The `types` parameter is optional and may contain any of:
	//
	//  - `world`: General knowledge about people, places, events, and things that happen
	//  - `experience`: Memories about experience, conversations, actions taken, and tasks performed
	//  - `observation`: Consolidated knowledge synthesized from facts
	//
	// If `types` is omitted, all fact types are recalled.
	//
	// POST /v1/default/banks/{bank_id}/memories/recall
	RecallMemories(ctx context.Context, req *RecallRequest, params RecallMemoriesParams) (RecallMemoriesRes, error)
	// RecoverConsolidation implements recover_consolidation operation.
	//
	// Reset all memories that were permanently marked as failed during consolidation (after exhausting all
	// LLM retries and adaptive batch splitting) so they are picked up again on the next consolidation run.
	// Does not delete any observations.
	//
	// POST /v1/default/banks/{bank_id}/consolidation/recover
	RecoverConsolidation(ctx context.Context, params RecoverConsolidationParams) (RecoverConsolidationRes, error)
	// Reflect implements reflect operation.
	//
	// Reflect and formulate an answer using bank identity, world facts, observations, and mental models.
	//
	// This endpoint:
	//
	// 1. Retrieves experience (conversations and events)
	// 2. Retrieves world facts relevant to the query
	// 3. Retrieves observations and mental models (bank's synthesized perspectives)
	// 4. Uses LLM to formulate a contextual answer
	// 5. Returns plain text answer and the facts used
	//
	// POST /v1/default/banks/{bank_id}/reflect
	Reflect(ctx context.Context, req *ReflectRequest, params ReflectParams) (ReflectRes, error)
	// RefreshMentalModel implements refresh_mental_model operation.
	//
	// Submit an async task to re-run the source query through reflect and update the content.
	//
	// POST /v1/default/banks/{bank_id}/mental-models/{mental_model_id}/refresh
	RefreshMentalModel(ctx context.Context, params RefreshMentalModelParams) (RefreshMentalModelRes, error)
	// RegenerateEntityObservations implements regenerate_entity_observations operation.
	//
	// This endpoint is deprecated. Entity observations have been replaced by mental models.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// POST /v1/default/banks/{bank_id}/entities/{entity_id}/regenerate
	RegenerateEntityObservations(ctx context.Context, params RegenerateEntityObservationsParams) (RegenerateEntityObservationsRes, error)
	// ReprocessDocument implements reprocess_document operation.
	//
	// Re-run the retain pipeline on an existing document without changing its content. This deletes the
	// existing memory units and re-extracts facts using the current engine configuration. Useful when the
	// LLM model, chunking strategy, or extraction settings have changed.
	//
	// POST /v1/default/banks/{bank_id}/documents/{document_id}/reprocess
	ReprocessDocument(ctx context.Context, params ReprocessDocumentParams) (ReprocessDocumentRes, error)
	// ResetBankConfig implements reset_bank_config operation.
	//
	// Reset bank configuration to defaults by removing all bank-specific overrides. The bank will then use
	// global and tenant-level configuration only.
	//
	// DELETE /v1/default/banks/{bank_id}/config
	ResetBankConfig(ctx context.Context, params ResetBankConfigParams) (ResetBankConfigRes, error)
	// RetainMemories implements retain_memories operation.
	//
	// Retain memory items with automatic fact extraction.
	//
	// This is the main endpoint for storing memories. It supports both synchronous and asynchronous
	// processing via the `async` parameter.
	//
	// Features:
	//
	//  - Efficient batch processing
	//  - Automatic fact extraction from natural language
	//  - Entity recognition and linking
	//  - Document tracking with automatic upsert (when document_id is provided)
	//  - Temporal and semantic linking
	//  - Optional asynchronous processing
	//
	// The system automatically:
	//
	// 1. Extracts semantic facts from the content
	// 2. Generates embeddings
	// 3. Deduplicates similar facts
	// 4. Creates temporal, semantic, and entity links
	// 5. Tracks document metadata
	//
	// When `async=true`: Returns immediately after queuing. Use the operations endpoint to monitor
	// progress.
	//
	// When `async=false` (default): Waits for processing to complete.
	//
	// Note: If a memory item has a `document_id` that already exists, the old document and its memory
	// units will be deleted before creating new ones (upsert behavior).
	//
	// POST /v1/default/banks/{bank_id}/memories
	RetainMemories(ctx context.Context, req *RetainRequest, params RetainMemoriesParams) (RetainMemoriesRes, error)
	// RetryOperation implements retry_operation operation.
	//
	// Re-queue a failed async operation so the worker picks it up again.
	//
	// POST /v1/default/banks/{bank_id}/operations/{operation_id}/retry
	RetryOperation(ctx context.Context, params RetryOperationParams) (RetryOperationRes, error)
	// SearchKnowledgeBase implements search_knowledge_base operation.
	//
	// Doc-level hybrid search across a bank's knowledge pages: a full-text (BM25) match and a
	// vector-similarity match, Reciprocal-Rank-Fusion fused. No reranker — tuned for latency.
	//
	// GET /v1/default/banks/{bank_id}/knowledge-base/search
	SearchKnowledgeBase(ctx context.Context, params SearchKnowledgeBaseParams) (SearchKnowledgeBaseRes, error)
	// SetBankAliasPrimary implements set_bank_alias_primary operation.
	//
	// Present the bank under one of its aliases. Purely cosmetic: the bank keeps its own `bank_id`, which
	// every other part of the system — authorisation, metering, exports, audit logs — continues to
	// use.
	//
	// Promoting an alias demotes whichever one was shown before, so a bank is presented under at most one
	// alias. Send `primary: false` to go back to showing its own id.
	//
	// PATCH /v1/default/banks/{bank_id}/aliases/{alias}
	SetBankAliasPrimary(ctx context.Context, req *SetBankAliasPrimaryRequest, params SetBankAliasPrimaryParams) (SetBankAliasPrimaryRes, error)
	// TestBankLlm implements test_bank_llm operation.
	//
	// Probe the LLMs this bank would use for retain / consolidation / reflect with one minimal call each
	// (configs shared across operations are probed once), so you can discover 'not configured /
	// unreachable' instead of a silent stall. Deliberate action (makes a real provider call); not for
	// polling. Returns status only — never the provider, model, endpoint, API key, or raw error. Disable
	// with HINDSIGHT_API_ENABLE_BANK_LLM_HEALTH=false.
	//
	// POST /v1/default/banks/{bank_id}/health/llm
	TestBankLlm(ctx context.Context, params TestBankLlmParams) (TestBankLlmRes, error)
	// TriggerConsolidation implements trigger_consolidation operation.
	//
	// Run memory consolidation to create/update observations from recent memories.
	//
	// POST /v1/default/banks/{bank_id}/consolidate
	TriggerConsolidation(ctx context.Context, req OptConsolidationRequest, params TriggerConsolidationParams) (TriggerConsolidationRes, error)
	// UpdateBank implements update_bank operation.
	//
	// Partially update an agent's profile. Only provided fields will be updated.
	//
	// PATCH /v1/default/banks/{bank_id}
	UpdateBank(ctx context.Context, req *CreateBankRequest, params UpdateBankParams) (UpdateBankRes, error)
	// UpdateBankConfig implements update_bank_config operation.
	//
	// Update configuration overrides for a bank. Only hierarchical behavioral settings can be overridden
	// (retention parameters, recall settings, etc.). Keys can be provided in Python field format
	// (retain_extraction_mode) or environment variable format (HINDSIGHT_API_RETAIN_EXTRACTION_MODE).
	//
	// PATCH /v1/default/banks/{bank_id}/config
	UpdateBankConfig(ctx context.Context, req *BankConfigUpdate, params UpdateBankConfigParams) (UpdateBankConfigRes, error)
	// UpdateBankDisposition implements update_bank_disposition operation.
	//
	// Removed. The bank profile endpoints have been removed. Disposition traits and the reflect mission
	// are bank configuration: read them from GET /v1/default/banks/{bank_id}/config as
	// `disposition_skepticism`, `disposition_literalism`, `disposition_empathy` and `reflect_mission`, and
	// write them with PATCH /v1/default/banks/{bank_id}/config. The `name` field this endpoint also
	// returned was a display-only label; read it from GET /v1/default/banks.
	//
	// Deprecated: schema marks this operation as deprecated.
	//
	// PUT /v1/default/banks/{bank_id}/profile
	UpdateBankDisposition(ctx context.Context, req *UpdateDispositionRequest, params UpdateBankDispositionParams) (UpdateBankDispositionRes, error)
	// UpdateDirective implements update_directive operation.
	//
	// Update a directive's properties.
	//
	// PATCH /v1/default/banks/{bank_id}/directives/{directive_id}
	UpdateDirective(ctx context.Context, req *UpdateDirectiveRequest, params UpdateDirectiveParams) (UpdateDirectiveRes, error)
	// UpdateDocument implements update_document operation.
	//
	// Update mutable fields on a document without re-processing its content.
	//
	// Tags (`tags`): The array REPLACES the document's tags, it is not merged into them — send the
	// complete set you want the document to end up with, and any tag you leave out is dropped. An empty
	// array (`[]`) therefore clears every tag; only omitting the field entirely is rejected (422).
	//
	// The new tags are propagated to all associated memory units. Observations derived from those units
	// are invalidated and queued for re-consolidation under the new tags. Co-source memories from other
	// documents that shared those observations are also reset. Tags are compared as a set, so re-sending
	// the tags a document already has (in any order) changes nothing and queues no re-consolidation.
	//
	// At least one field must be provided.
	//
	// PATCH /v1/default/banks/{bank_id}/documents/{document_id}
	UpdateDocument(ctx context.Context, req *UpdateDocumentRequest, params UpdateDocumentParams) (UpdateDocumentRes, error)
	// UpdateKnowledgeNode implements update_knowledge_node operation.
	//
	// Rename a node (set `name`), move it under another folder (set `parent_id`, null for the root),
	// and/or update a page's options (`source_query`, `tags`, `max_tokens`, `trigger`). Changing
	// `source_query` schedules an async refresh so the page rebuilds against the new question. `trigger`
	// is applied as a patch: the fields you send are updated and the rest keep the page's current values.
	//
	// PATCH /v1/default/banks/{bank_id}/knowledge-base/nodes/{node_id}
	UpdateKnowledgeNode(ctx context.Context, req *UpdateNodeRequest, params UpdateKnowledgeNodeParams) (UpdateKnowledgeNodeRes, error)
	// UpdateMemory implements update_memory operation.
	//
	// Edit a memory's text and/or change its curation state (invalidate / revert). Invalidated memories
	// are excluded from recall, consolidation, and graph maintenance but kept for audit (reversible). Only
	// world/experience facts can be curated; observations are derived.
	//
	// PATCH /v1/default/banks/{bank_id}/memories/{memory_id}
	UpdateMemory(ctx context.Context, req *UpdateMemoryRequest, params UpdateMemoryParams) (UpdateMemoryRes, error)
	// UpdateMentalModel implements update_mental_model operation.
	//
	// Update a mental model's name and/or source query.
	//
	// PATCH /v1/default/banks/{bank_id}/mental-models/{mental_model_id}
	UpdateMentalModel(ctx context.Context, req *UpdateMentalModelRequest, params UpdateMentalModelParams) (UpdateMentalModelRes, error)
	// UpdateWebhook implements update_webhook operation.
	//
	// Update one or more fields of a registered webhook. Only provided fields are changed.
	//
	// PATCH /v1/default/banks/{bank_id}/webhooks/{webhook_id}
	UpdateWebhook(ctx context.Context, req *UpdateWebhookRequest, params UpdateWebhookParams) (UpdateWebhookRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
