// Code generated by ogen, DO NOT EDIT.

package api

// setDefaults set default value of fields.
func (s *AddBackgroundRequest) setDefaults() {
	{
		val := bool(true)
		s.UpdateDisposition.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BankAliasEntry) setDefaults() {
	{
		val := bool(false)
		s.Primary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BankListItem) setDefaults() {
	{
		val := int(0)
		s.FactCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BankStatsResponse) setDefaults() {
	{
		val := int(0)
		s.PendingConsolidation.SetTo(val)
	}
	{
		val := int(0)
		s.FailedConsolidation.SetTo(val)
	}
	{
		val := int(0)
		s.TotalObservations.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BankTemplateDirective) setDefaults() {
	{
		val := int(0)
		s.Priority.SetTo(val)
	}
	{
		val := bool(true)
		s.IsActive.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *BankTemplateImportResponse) setDefaults() {
	{
		var defaultVal0 []string
		s.MentalModelsCreated = defaultVal0
	}
	{
		var defaultVal0 []string
		s.MentalModelsUpdated = defaultVal0
	}
	{
		var defaultVal0 []string
		s.DirectivesCreated = defaultVal0
	}
	{
		var defaultVal0 []string
		s.DirectivesUpdated = defaultVal0
	}
	{
		var defaultVal0 []string
		s.OperationIds = defaultVal0
	}
	{
		val := bool(false)
		s.DryRun.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BankTemplateMentalModel) setDefaults() {
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
	{
		val := int(2048)
		s.MaxTokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *BankTransferSubmitResponse) setDefaults() {
	{
		val := string("pending")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *Base64AttachmentSource) setDefaults() {
	{
		val := string("base64")
		s.Type.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChunkData) setDefaults() {
	{
		val := bool(false)
		s.Truncated.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ChunkIncludeOptions) setDefaults() {
	{
		val := int(8192)
		s.MaxTokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConsolidationResponse) setDefaults() {
	{
		val := bool(false)
		s.Deduplicated.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ConsolidationStrategiesPreviewRequest) setDefaults() {
	{
		val := int(5)
		s.SampleLimit.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateBankAliasRequest) setDefaults() {
	{
		val := bool(false)
		s.Primary.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateDirectiveRequest) setDefaults() {
	{
		val := int(0)
		s.Priority.SetTo(val)
	}
	{
		val := bool(true)
		s.IsActive.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *CreateMentalModelRequest) setDefaults() {
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
	{
		val := int(2048)
		s.MaxTokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *CreateWebhookRequest) setDefaults() {
	{
		var defaultVal0 []string
		{
			var defaultVal0Elem string

			val := string("consolidation.completed")
			defaultVal0Elem = val
			defaultVal0 = append(defaultVal0, defaultVal0Elem)
		}
		s.EventTypes = defaultVal0
	}
	{
		val := bool(true)
		s.Enabled.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DirectiveResponse) setDefaults() {
	{
		val := int(0)
		s.Priority.SetTo(val)
	}
	{
		val := bool(true)
		s.IsActive.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *DocumentExportSubmitResponse) setDefaults() {
	{
		val := string("pending")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DocumentImportSubmitResponse) setDefaults() {
	{
		val := string("pending")
		s.Status.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *DocumentListItem) setDefaults() {
	{
		val := string("")
		s.BankID.SetTo(val)
	}
	{
		val := string("")
		s.CreatedAt.SetTo(val)
	}
	{
		val := string("")
		s.UpdatedAt.SetTo(val)
	}
	{
		val := int(0)
		s.TextLength.SetTo(val)
	}
	{
		val := int(0)
		s.MemoryUnitCount.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *DocumentResponse) setDefaults() {
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *DryRunExtractRequest) setDefaults() {
	{
		val := string("")
		s.Context.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityGraphEdgeData) setDefaults() {
	{
		val := string("cooccurrence")
		s.LinkType.SetTo(val)
	}
	{
		val := int(0)
		s.Weight.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityGraphNodeData) setDefaults() {
	{
		val := string("")
		s.Label.SetTo(val)
	}
	{
		val := int(0)
		s.MentionCount.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *EntityIncludeOptions) setDefaults() {
	{
		val := int(500)
		s.MaxTokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *KnowledgeNode) setDefaults() {
	{
		val := bool(false)
		s.Managed.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
	{
		var defaultVal0 []KnowledgeNode
		s.Children = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *KnowledgePageResponse) setDefaults() {
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *LabelGroupInput) setDefaults() {
	{
		val := string("")
		s.Description.SetTo(val)
	}
	{
		val := LabelGroupInputType("value")
		s.Type.SetTo(val)
	}
	{
		val := bool(true)
		s.Optional.SetTo(val)
	}
	{
		val := bool(false)
		s.Tag.SetTo(val)
	}
	{
		var defaultVal0 []LabelValue
		s.Values = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *LabelGroupOutput) setDefaults() {
	{
		val := string("")
		s.Description.SetTo(val)
	}
	{
		val := LabelGroupOutputType("value")
		s.Type.SetTo(val)
	}
	{
		val := bool(true)
		s.Optional.SetTo(val)
	}
	{
		val := bool(false)
		s.Tag.SetTo(val)
	}
	{
		var defaultVal0 []LabelValue
		s.Values = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *LabelValue) setDefaults() {
	{
		val := string("")
		s.Description.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MapFieldInput) setDefaults() {
	{
		val := MapFieldInputType("text")
		s.Type.SetTo(val)
	}
	{
		val := string("")
		s.Description.SetTo(val)
	}
	{
		var defaultVal0 []LabelValue
		s.Values = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *MapFieldOutput) setDefaults() {
	{
		val := MapFieldOutputType("text")
		s.Type.SetTo(val)
	}
	{
		val := string("")
		s.Description.SetTo(val)
	}
	{
		var defaultVal0 []LabelValue
		s.Values = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *MemoriesTimeseriesResponse) setDefaults() {
	{
		val := string("created_at")
		s.TimeField.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MemoryGraphEdgeData) setDefaults() {
	{
		val := string("")
		s.LinkType.SetTo(val)
	}
	{
		val := float64(0)
		s.Weight.SetTo(val)
	}
	{
		val := string("")
		s.EntityName.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MemoryGraphNodeData) setDefaults() {
	{
		val := string("")
		s.Label.SetTo(val)
	}
	{
		val := string("")
		s.Text.SetTo(val)
	}
	{
		val := string("")
		s.Date.SetTo(val)
	}
	{
		val := string("")
		s.Context.SetTo(val)
	}
	{
		val := string("")
		s.Entities.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MemoryGraphTableRow) setDefaults() {
	{
		val := string("")
		s.Text.SetTo(val)
	}
	{
		val := string("")
		s.Context.SetTo(val)
	}
	{
		val := string("")
		s.Entities.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *MemoryItem) setDefaults() {
	{
		val := bool(true)
		s.ResolveEntities.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MemoryTimeseriesBucket) setDefaults() {
	{
		val := int(0)
		s.World.SetTo(val)
	}
	{
		val := int(0)
		s.Experience.SetTo(val)
	}
	{
		val := int(0)
		s.Observation.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MemoryUnitListItem) setDefaults() {
	{
		val := string("")
		s.Text.SetTo(val)
	}
	{
		val := string("")
		s.Context.SetTo(val)
	}
	{
		val := string("")
		s.Date.SetTo(val)
	}
	{
		val := string("")
		s.Entities.SetTo(val)
	}
	{
		val := int(1)
		s.ProofCount.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
	{
		val := string("valid")
		s.State.SetTo(val)
	}
	{
		var defaultVal0 []string
		s.SourceMemoryIds = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *MentalModelDryRunRefreshResult) setDefaults() {
	{
		val := int(0)
		s.DurationMs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MentalModelRefreshTrace) setDefaults() {
	{
		val := int(0)
		s.DurationMs.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MentalModelResponse) setDefaults() {
	{
		var defaultVal0 []string
		s.Tags = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *MentalModelTraceToolCall) setDefaults() {
	{
		val := int(0)
		s.Iteration.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MentalModelTriggerInput) setDefaults() {
	{
		val := Budget("mid")
		s.Budget.SetTo(val)
	}
	{
		val := MentalModelTriggerInputMode("full")
		s.Mode.SetTo(val)
	}
	{
		val := bool(false)
		s.RefreshAfterConsolidation.SetTo(val)
	}
	{
		val := bool(false)
		s.ExcludeMentalModels.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepTrace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *MentalModelTriggerOutput) setDefaults() {
	{
		val := Budget("mid")
		s.Budget.SetTo(val)
	}
	{
		val := MentalModelTriggerOutputMode("full")
		s.Mode.SetTo(val)
	}
	{
		val := bool(false)
		s.RefreshAfterConsolidation.SetTo(val)
	}
	{
		val := bool(false)
		s.ExcludeMentalModels.SetTo(val)
	}
	{
		val := bool(false)
		s.KeepTrace.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptBlockModel) setDefaults() {
	{
		val := string("")
		s.Field.SetTo(val)
	}
	{
		val := string("")
		s.Section.SetTo(val)
	}
	{
		val := string("")
		s.Heading.SetTo(val)
	}
	{
		val := bool(true)
		s.Active.SetTo(val)
	}
	{
		val := bool(false)
		s.Editable.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *PromptPreviewRequest) setDefaults() {
	{
		val := PromptPreviewRequestOperation("retain")
		s.Operation.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RecallRequest) setDefaults() {
	{
		val := bool(false)
		s.PreferObservations.SetTo(val)
	}
	{
		val := Budget("mid")
		s.Budget.SetTo(val)
	}
	{
		val := int(4096)
		s.MaxTokens.SetTo(val)
	}
	{
		val := bool(false)
		s.Trace.SetTo(val)
	}
	{
		val := RecallRequestTagsMatch("any")
		s.TagsMatch.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ReflectBasedOn) setDefaults() {
	{
		var defaultVal0 []ReflectFact
		s.Memories = defaultVal0
	}
	{
		var defaultVal0 []ReflectMentalModel
		s.MentalModels = defaultVal0
	}
	{
		var defaultVal0 []ReflectDirective
		s.Directives = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *ReflectRequest) setDefaults() {
	{
		val := Budget("mid")
		s.Budget.SetTo(val)
	}
	{
		val := int(4096)
		s.MaxTokens.SetTo(val)
	}
	{
		val := ReflectRequestTagsMatch("any")
		s.TagsMatch.SetTo(val)
	}
	{
		val := bool(false)
		s.ApplyAllDirectives.SetTo(val)
	}
	{
		val := bool(false)
		s.ExcludeMentalModels.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ReflectToolCall) setDefaults() {
	{
		val := int(0)
		s.Iteration.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ReflectTrace) setDefaults() {
	{
		var defaultVal0 []ReflectToolCall
		s.ToolCalls = defaultVal0
	}
	{
		var defaultVal0 []ReflectLLMCall
		s.LlmCalls = defaultVal0
	}
}

// setDefaults set default value of fields.
func (s *RefreshMentalModelOperationDetails) setDefaults() {
	{
		val := string("refresh_mental_model")
		s.OperationType.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RetainRequest) setDefaults() {
	{
		val := bool(false)
		s.Async.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *RunSettingModel) setDefaults() {
	{
		val := bool(false)
		s.Editable.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *SourceFactsIncludeOptions) setDefaults() {
	{
		val := int(4096)
		s.MaxTokens.SetTo(val)
	}
	{
		val := int(-1)
		s.MaxTokensPerObservation.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *TokenUsage) setDefaults() {
	{
		val := int(0)
		s.InputTokens.SetTo(val)
	}
	{
		val := int(0)
		s.OutputTokens.SetTo(val)
	}
	{
		val := int(0)
		s.TotalTokens.SetTo(val)
	}
	{
		val := int(0)
		s.CachedTokens.SetTo(val)
	}
	{
		val := int(0)
		s.ThoughtsTokens.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *ToolCallsIncludeOptions) setDefaults() {
	{
		val := bool(true)
		s.Output.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateDocumentResponse) setDefaults() {
	{
		val := bool(true)
		s.Success.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *UpdateMemoryRequest) setDefaults() {
	{
		val := bool(true)
		s.ResolveEntities.SetTo(val)
	}
}

// setDefaults set default value of fields.
func (s *WebhookHttpConfig) setDefaults() {
	{
		val := string("POST")
		s.Method.SetTo(val)
	}
	{
		val := int(30)
		s.TimeoutSeconds.SetTo(val)
	}
}
